server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true # access 로그 추가
##    basedir: /Users/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root@1234
    # initialization-mode: never # resource ? ?? schema.sql ? ?? (???: always, ????: never)
#  jpa: # DB ?? ?? ?? ??? ?? ??? ??? ??.
#    show-sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true # userDetailService ?? ??? ?? ?? ??? ??? ??? ??? ?? ??


